<?php
/**
 * <?tusk> Generated by TuskPHP CLI
 * Created: 2025-06-25 20:15:00
 * Strong. Secure. Scalable. 🐘
 *
 * <?tusk> footer Component
 * Auto-Inclusion: [tusk-component-footer]
 */
?>

<footer class="tusk-footer">
    <div class="footer-container">
        <div class="footer-content">
            <div class="footer-section">
                <h3>About TuskPHP</h3>
                <p>Strong. Secure. Scalable. Building the future with elephant wisdom.</p>
                <div class="social-links">
                    <a href="#" class="social-link">📘</a>
                    <a href="#" class="social-link">🐦</a>
                    <a href="#" class="social-link">💼</a>
                    <a href="#" class="social-link">📸</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h3>Quick Links</h3>
                <ul class="footer-links">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            
            <div class="footer-section">
                <h3>Newsletter</h3>
                <p>Stay updated with our latest news</p>
                <div class="newsletter-form">
                    <input type="email" placeholder="Enter your email" class="newsletter-input">
                    <button class="newsletter-btn">Subscribe</button>
                </div>
            </div>
        </div>
        
        <div class="footer-bottom">
            <p>&copy; 2024 TuskPHP. All rights reserved. 🐘</p>
        </div>
    </div>
</footer>