<?php
/**
 * <?tusk> Generated by TuskPHP CLI
 * Created: 2025-06-25 20:15:00
 * Strong. Secure. Scalable. 🐘
 *
 * <?tusk> hero Component
 * Auto-Inclusion: [tusk-component-hero]
 */
?>

<section class="tusk-hero-hero" id="home">
    <div class="hero-container">
        <div class="hero-content">
            <h1 id="hero-title">Welcome to TuskPHP</h1>
            <p id="hero-subtitle">Strong. Secure. Scalable. Building the future with elephant wisdom.</p>
            <div class="hero-cta">
                <button class="btn btn-primary" onclick="scrollToSection('about')">Discover More</button>
                <button class="btn btn-secondary" onclick="openModal('demo-modal')" style="margin-left: 1rem;">View Demo</button>
            </div>
        </div>
        
        <!-- Floating elements for visual interest -->
        <div class="hero-floaters">
            <div class="floater" style="top: 20%; left: 10%; animation-delay: 0s;">🐘</div>
            <div class="floater" style="top: 60%; right: 15%; animation-delay: 1s;">⚡</div>
            <div class="floater" style="top: 30%; right: 25%; animation-delay: 2s;">🚀</div>
            <div class="floater" style="bottom: 30%; left: 20%; animation-delay: 3s;">💎</div>
        </div>
    </div>
</section>

<style>
.floater {
    position: absolute;
    font-size: 2rem;
    opacity: 0.3;
    animation: float 6s ease-in-out infinite;
}

@keyframes float {
    0%, 100% { transform: translateY(0px) rotate(0deg); }
    33% { transform: translateY(-20px) rotate(5deg); }
    66% { transform: translateY(10px) rotate(-5deg); }
}

.hero-floaters {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    pointer-events: none;
}
</style>

<script>
function scrollToSection(sectionId) {
    const element = document.getElementById(sectionId);
    const navbar = document.getElementById('tusk-navbar');
    if (element) {
        const offsetTop = element.offsetTop - (navbar ? navbar.offsetHeight : 0);
        window.scrollTo({
            top: offsetTop,
            behavior: 'smooth'
        });
    }
}

function openModal(modalId) {
    const modal = document.getElementById(modalId);
    if (modal) {
        modal.classList.add('active');
        document.body.style.overflow = 'hidden';
    }
}

// Typing animation for hero title
document.addEventListener('DOMContentLoaded', function() {
    const title = document.getElementById('hero-title');
    const text = title.textContent;
    title.textContent = '';
    
    let i = 0;
    function typeWriter() {
        if (i < text.length) {
            title.textContent += text.charAt(i);
            i++;
            setTimeout(typeWriter, 100);
        }
    }
    
    setTimeout(typeWriter, 500);
});
</script>