<?php
/**
 * <?tusk> Generated by TuskPHP CLI
 * Created: 2025-06-25 20:15:00
 * Strong. Secure. Scalable. 🐘
 *
 * <?tusk> hero-animated Component
 * Auto-Inclusion: [tusk-component-hero-animated]
 */
?>

<section class="tusk-hero-hero-animated">
    <div class="hero-container">
        <h2>Hero Animated</h2>
        <p>This is a hero component. Customize it to fit your needs!</p>
    </div>
</section>

<style>
.tusk-hero-hero-animated {
    padding: 3rem 0;
    text-align: center;
    background: #f9fafb;
}

.hero-container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 2rem;
}
</style>