<?php
/**
 * <?tusk> Generated by TuskPHP CLI
 * Created: 2025-06-25 20:15:00
 * Strong. Secure. Scalable. 🐘
 *
 * <?tusk> navbar Component
 * Auto-Inclusion: [tusk-component-navbar]
 */
?>

<nav class="tusk-navbar" id="tusk-navbar">
    <div class="navbar-container">
        <div class="navbar-brand">
            <img src="/assets/logos/blb-family.png" alt="TuskPHP Logo" class="navbar-logo">
            <span class="brand-text">TuskPHP</span>
        </div>
        
        <div class="navbar-menu" id="navbar-menu">
            <a href="#home" class="navbar-link" data-scroll="home">Home</a>
            <a href="#about" class="navbar-link" data-scroll="about">About</a>
            <a href="#services" class="navbar-link" data-scroll="services">Services</a>
            <a href="#contact" class="navbar-link" data-scroll="contact">Contact</a>
            <a href="#blog" class="navbar-link" data-scroll="blog">Blog</a>
        </div>
        
        <div class="navbar-toggle" id="navbar-toggle">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</nav>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const toggle = document.getElementById('navbar-toggle');
    const menu = document.getElementById('navbar-menu');
    const navbar = document.getElementById('tusk-navbar');
    const navLinks = document.querySelectorAll('.navbar-link[data-scroll]');
    
    // Mobile menu toggle
    toggle.addEventListener('click', function() {
        menu.classList.toggle('active');
        
        // Animate hamburger
        const spans = toggle.querySelectorAll('span');
        if (menu.classList.contains('active')) {
            spans[0].style.transform = 'rotate(45deg) translate(5px, 5px)';
            spans[1].style.opacity = '0';
            spans[2].style.transform = 'rotate(-45deg) translate(7px, -6px)';
        } else {
            spans[0].style.transform = 'none';
            spans[1].style.opacity = '1';
            spans[2].style.transform = 'none';
        }
    });
    
    // Smooth scrolling for navigation links
    navLinks.forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            const targetId = this.getAttribute('data-scroll');
            const targetElement = document.getElementById(targetId);
            
            if (targetElement) {
                const offsetTop = targetElement.offsetTop - navbar.offsetHeight;
                window.scrollTo({
                    top: offsetTop,
                    behavior: 'smooth'
                });
            }
            
            // Close mobile menu if open
            menu.classList.remove('active');
            const spans = toggle.querySelectorAll('span');
            spans[0].style.transform = 'none';
            spans[1].style.opacity = '1';
            spans[2].style.transform = 'none';
        });
    });
    
    // Navbar scroll effect
    window.addEventListener('scroll', function() {
        if (window.scrollY > 100) {
            navbar.style.background = 'linear-gradient(135deg, rgba(102, 126, 234, 0.95) 0%, rgba(118, 75, 162, 0.95) 100%)';
            navbar.style.backdropFilter = 'blur(10px)';
        } else {
            navbar.style.background = 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)';
            navbar.style.backdropFilter = 'none';
        }
    });
    
    // Active link highlighting
    window.addEventListener('scroll', function() {
        const scrollPos = window.scrollY + navbar.offsetHeight + 100;
        
        navLinks.forEach(link => {
            const targetId = link.getAttribute('data-scroll');
            const targetElement = document.getElementById(targetId);
            
            if (targetElement) {
                const elementTop = targetElement.offsetTop;
                const elementBottom = elementTop + targetElement.offsetHeight;
                
                if (scrollPos >= elementTop && scrollPos < elementBottom) {
                    navLinks.forEach(l => l.classList.remove('active'));
                    link.classList.add('active');
                }
            }
        });
    });
});
</script>