<?php
/**
 * <?tusk> Generated by TuskPHP CLI
 * Created: 2025-06-25 20:15:00
 * Strong. Secure. Scalable. 🐘
 *
 * <?tusk> sidebar Component
 * Auto-Inclusion: [tusk-component-sidebar]
 */
?>

<aside class="tusk-sidebar" id="tusk-sidebar">
    <div class="sidebar-header">
        <h3>🐘 Navigation</h3>
        <button class="sidebar-toggle" id="sidebar-toggle">×</button>
    </div>
    
    <nav class="sidebar-nav">
        <ul class="sidebar-menu">
            <li class="sidebar-item">
                <a href="#" class="sidebar-link active">
                    <span class="sidebar-icon">🏠</span>
                    Dashboard
                </a>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link">
                    <span class="sidebar-icon">👥</span>
                    Users
                </a>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link">
                    <span class="sidebar-icon">📊</span>
                    Analytics
                </a>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link">
                    <span class="sidebar-icon">⚙️</span>
                    Settings
                </a>
            </li>
        </ul>
    </nav>
</aside>

<div class="sidebar-overlay" id="sidebar-overlay"></div>

<style>
.tusk-sidebar {
    position: fixed;
    top: 0;
    left: -300px;
    width: 300px;
    height: 100vh;
    background: linear-gradient(180deg, #2c3e50 0%, #34495e 100%);
    color: white;
    transition: left 0.3s ease;
    z-index: 1000;
    overflow-y: auto;
}

.tusk-sidebar.active {
    left: 0;
}

.sidebar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.5rem;
    border-bottom: 1px solid #34495e;
}

.sidebar-toggle {
    background: none;
    border: none;
    color: white;
    font-size: 1.5rem;
    cursor: pointer;
}

.sidebar-nav {
    padding: 1rem 0;
}

.sidebar-menu {
    list-style: none;
    padding: 0;
    margin: 0;
}

.sidebar-item {
    margin-bottom: 0.5rem;
}

.sidebar-link {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 1rem 1.5rem;
    color: #bdc3c7;
    text-decoration: none;
    transition: all 0.3s ease;
}

.sidebar-link:hover,
.sidebar-link.active {
    background: #34495e;
    color: #ffd700;
    border-right: 3px solid #ffd700;
}

.sidebar-icon {
    font-size: 1.2rem;
}

.sidebar-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    z-index: 999;
    opacity: 0;
    visibility: hidden;
    transition: all 0.3s ease;
}

.sidebar-overlay.active {
    opacity: 1;
    visibility: visible;
}

@media (min-width: 768px) {
    .tusk-sidebar {
        position: relative;
        left: 0;
    }
    
    .sidebar-overlay {
        display: none;
    }
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const sidebar = document.getElementById('tusk-sidebar');
    const toggle = document.getElementById('sidebar-toggle');
    const overlay = document.getElementById('sidebar-overlay');
    
    function toggleSidebar() {
        sidebar.classList.toggle('active');
        overlay.classList.toggle('active');
    }
    
    toggle.addEventListener('click', toggleSidebar);
    overlay.addEventListener('click', toggleSidebar);
});
</script>